name: 'BigExcelCreator-CI'

trigger:
  branches:
    include:
      - main
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

parameters:
- name: doNugetPush
  displayName: 'Publish NuGet Package'
  type: boolean
  default: false   # automatic runs will not push
- name: doDocFxPublish
  displayName: 'Publish DocFX Documentation'
  type: boolean
  default: false   # automatic runs will not push

variables:
  solution: '**/*.sln'
  mainProject: 'BigExcelCreator/BigExcelCreator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: wait_for_sonar
  displayName: 'Wait for SonarQube Analysis'
  jobs:
  - job: wait_for_sonar_job
    displayName: 'Ensure SonarQube Analysis Completed'
    steps:
    - template: Common/ensure-pipeline-run.yaml
      parameters:
        org: fenase
        project: BigExcelCreator
        pipelineId: 17   # definitionId of BigExcelCreator-sonar
        timeoutMinutes: 20

- stage: build_test_and_package
  displayName: 'Build, Test, and Package'
  dependsOn: wait_for_sonar
  jobs:
  - job: build_and_test_job
    displayName: 'Build, Test, and Package Job'
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      fetchTags: true
      displayName: 'git checkout'
      enabled: true
      retryCountOnTaskFailure: 2

    - template: Common/InstallEnvironment.yaml

    - template: Common/build.yaml

    - template: Common/test.yaml

    - task: DotNetCoreCLI@2
      displayName: 'NuGet Pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(mainProject)'
        versioningScheme: 'off'

    # Conditional NuGet Push
    - task: NuGetCommand@2
      displayName: 'NuGet Push'
      condition: eq('${{ parameters.doNugetPush }}', true)
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget BigExcel'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        publishLocation: 'pipeline'
      
- stage: publish_docfx
  displayName: 'Publish DocFX Documentation'
  dependsOn: build_test_and_package
  condition: eq('${{ parameters.doDocFxPublish }}', true)
  jobs:
  - job: publish_docfx_job
    displayName: 'Publish DocFX Documentation Job'
    pool:
      vmImage: ubuntu-latest
    steps:
      # Step 1: Install DocFX
      - template: Common/InstallEnvironment.yaml

      - script: |
          dotnet tool install -g docfx
        displayName: 'Install DocFX'

      # Step 2: Build the Documentation using DocFX
      - script: |
          docfx docfx.json
        displayName: 'Build Documentation'

      # Step 3: Deploy to GitHub Pages
      # - task: Bash@3
      #   displayName: 'Deploy to GitHub Pages'
      #   inputs:
      #     targetType: 'inline'
      #     script: |
      #       git config --global user.email "your-email@example.com"
      #       git config --global user.name "Your Name"
      #       git clone --branch gh-pages https://$GITHUB_PAT@github.com/$GITHUB_REPO.git out
      #       rm -rf out/*
      #       cp -r _site/* out/
      #       cd out
      #       git add --all
      #       git commit -m "Update documentation"
      #       git push origin gh-pages
        env:
          GITHUB_PAT: $(GITHUB_PAT)  # The GitHub Personal Access Token
          GITHUB_REPO: fenase/BigExcelCreator  # Update with your repo details

