name: 'BigExcelCreator-CI'

trigger:
  branches:
    exclude:
      - 'gh-pages'
    include:
      - '*'
   
pr:
  autoCancel: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

parameters:
- name: doNugetPush
  displayName: 'Publish NuGet Package'
  type: boolean
  default: false   # automatic runs will not push
- name: doDocFxPublish
  displayName: 'Publish DocFX Documentation'
  type: boolean
  default: false   # automatic runs will not push

variables:
  solution: '**/*.sln'
  mainProject: 'BigExcelCreator/BigExcelCreator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Start
  displayName: 'Start Stage'
  jobs:
  - job: StartJob
    displayName: 'Start Job'
    steps:
    - checkout: none
    - script: echo "Starting the BigExcelCreator-CI pipeline"
      displayName: 'Start Script'

- stage: SonarBuild
  displayName: 'Analize with SonarCloud'
  dependsOn: Start
  jobs:
  - job: SonarBuildJob
    displayName: 'Prepare, Build, and Analyze'
    steps:
    - template: StageTemplates/sonar.yml

- stage: build_test_and_package
  displayName: 'Build, Test, and Package'
  dependsOn:
    - Start
    - ${{ if eq(parameters.doNugetPush, true) }}:
      - SonarBuild
  jobs:
  - job: build_and_test_job
    displayName: 'Build, Test, and Package Job'
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      fetchTags: true
      displayName: 'Git checkout'
      enabled: true
      retryCountOnTaskFailure: 2

    - template: Common/InstallEnvironment.yaml

    - template: Common/build.yaml

    - template: Common/test.yaml

    - task: DotNetCoreCLI@2
      displayName: 'NuGet Pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(mainProject)'
        arguments: '-c $(buildConfiguration) --no-build'
        nobuild: true
        versioningScheme: 'off'

    # Conditional NuGet Push
    - ${{ if eq(parameters.doNugetPush, true) }}:
      - task: NuGetCommand@2
        displayName: 'NuGet Push'
        condition: ${{ eq(parameters.doNugetPush, true) }}
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'Nuget BigExcel'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'build_test_and_package Workspace'
        publishLocation: 'pipeline'
     
- ${{ if eq(parameters.doDocFxPublish, true) }}:  
  - stage: publish_docfx
    displayName: 'Publish DocFX Documentation'
    condition: ${{ eq(parameters.doDocFxPublish, true) }}
    dependsOn:
      - SonarBuild
      - ${{ if eq(parameters.doNugetPush, true) }}:
        - build_test_and_package
    jobs:
    - job: publish_docfx_job
      displayName: 'Publish DocFX Documentation Job'
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self
          fetchDepth: 0
          clean: true
          fetchTags: true
          displayName: 'Git Checkout'
          enabled: true
          retryCountOnTaskFailure: 2
          
        # Step 1: Install DocFX
        - template: /.azure/Common/InstallEnvironment.yaml

        - script: |
            dotnet tool install -g docfx
          displayName: 'Install DocFX'

        # Step 2: Build the Documentation using DocFX
        - script: |
            docfx docfx.json
          displayName: 'Build Documentation'

        # Step 3: Deploy to GitHub Pages
        - task: Bash@3
          displayName: 'Deploy to GitHub Pages'
          inputs:
            targetType: 'inline'
            script: |
              export GITHUB_PAT="$GITHUB_PAT"
              export GITHUB_REPO="$GITHUB_REPO"

              git config --global user.email "your-email@example.com"
              git config --global user.name "Your Name"
              git clone --branch gh-pages https://$GITHUB_PAT@github.com/$GITHUB_REPO.git out
              rm -rf out/*
              cp -r _site/* out/
              cd out
              git add --all
              git commit -m "Update documentation"
              git push origin gh-pages
          env:
            GITHUB_PAT: $(GITHUB_PAT)  # The GitHub Personal Access Token
            GITHUB_REPO: fenase/BigExcelCreator  # Update with your repo details
      