name: 'BigExcelCreator-CI'

trigger:
  branches:
    include:
      - main
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  mainProject: 'BigExcelCreator/BigExcelCreator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: NuGetBuild
  displayName: 'Build and Publish NuGet Package'
  jobs:
  - job: NuGetBuildJob
    displayName: 'Build and Publish'

    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      fetchTags: true
      displayName: 'git checkout'
      enabled: true
      retryCountOnTaskFailure: 2

    # Prepare environment (SDKs, NuGet, etc.)
    - template: Common/InstallEnvironment.yaml

    # Ensure sonar pipeline has run before continuing
    - template: ensure-pipeline-run.yaml
      parameters:
        org: 'fenase'
        project: 'BigExcelCreator'
        pipelineId: 18   # definitionId of BigExcelCreator-sonar
        timeoutMinutes: 20

    # Build solution
    - template: Common/build.yaml

    # Run tests
    - task: VSTest@3
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\bin\**\*.test.dll
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        diagnosticsEnabled: true

    # Pack NuGet
    - task: DotNetCoreCLI@2
      displayName: 'NuGet Pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(mainProject)'
        versioningScheme: 'off'

    # Publish artifacts so the next job can use them
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'nuget-packages'
        publishLocation: 'pipeline'

  - job: NuGetPushJob
    displayName: 'NuGet Push (requires approval)'
    dependsOn: NuGetBuildJob
    pool:
      vmImage: 'windows-latest'
    environment: 'nuget-publish'   # <-- configure this environment in DevOps with approvals
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'nuget-packages'
        targetPath: '$(Build.ArtifactStagingDirectory)'

    # Push NuGet
    - task: NuGetCommand@2
      displayName: 'NuGet Push'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget BigExcel'

    # Publish artifacts
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        publishLocation: 'pipeline'
