name: 'BigExcelCreator-CI'

trigger:
  branches:
    include:
      - main
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  mainProject: 'BigExcelCreator/BigExcelCreator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: NuGetBuild
  displayName: 'Build and Publish NuGet Package'
  jobs:
  - job: NuGetBuildJob
    displayName: 'Build and Pack'
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      fetchTags: true
      displayName: 'git checkout'
      enabled: true
      retryCountOnTaskFailure: 2

    # Prepare environment (SDKs, NuGet, etc.)
    - template: Common/InstallEnvironment.yaml

    # Ensure sonar pipeline has run before continuing
    - template: Common/ensure-pipeline-run.yaml
      parameters:
        org: 'fenase'
        project: 'BigExcelCreator'
        pipelineId: 18   # definitionId of BigExcelCreator-sonar
        timeoutMinutes: 20

    # Build solution
    - template: Common/build.yaml

    # Run tests
    - task: VSTest@3
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\bin\**\*.test.dll
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        diagnosticsEnabled: true

    # Pack NuGet
    - task: DotNetCoreCLI@2
      displayName: 'NuGet Pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(mainProject)'
        versioningScheme: 'off'

    # Publish the package as an artifact for the next job
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'nuget-packages'
        publishLocation: 'pipeline'

  # Deployment job for NuGet Push, tied to environment with approvals
  - deployment: NuGetPushJob
    displayName: 'NuGet Push (requires approval)'
    dependsOn: NuGetBuildJob
    environment: 'nuget-publish'   # <-- configure this environment in DevOps with approvals
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                artifactName: 'nuget-packages'
                targetPath: '$(Pipeline.Workspace)'

            # Push NuGet
            - task: NuGetCommand@2
              displayName: 'NuGet Push'
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'Nuget BigExcel'

            # Publish artifacts
            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: '$(Pipeline.Workspace)'
                publishLocation: 'pipeline'
