name: 'BigExcelCreator-sonar'

trigger:
  branches:
    exclude:
      - 'azure-pipelines'
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  mainProject: 'BigExcelCreator/BigExcelCreator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: SonarBuild
  displayName: 'Build and analize with SonarCloud'
  jobs:
  - job: SonarBuildJob
    displayName: 'Prepare, Build, and Analyze'
    steps:
    - template: StageTemplates/sonar.yml
