name: 'BigExcelCreator-CI'

trigger:
  branches:
    exclude:
      - 'azure-pipelines'
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

parameters:
- name: doNugetPush
  displayName: 'Publish NuGet Package'
  type: boolean
  default: false   # automatic runs will not push
- name: doDocFxPublish
  displayName: 'Publish DocFX Documentation'
  type: boolean
  default: false   # automatic runs will not push

variables:
  solution: '**/*.sln'
  mainProject: 'BigExcelCreator/BigExcelCreator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:


- stage: SonarBuild
  dependsOn: []
  displayName: 'Build and analize with SonarCloud'
  jobs:
  - job: SonarBuildJob
    displayName: 'Prepare, Build, and Analyze'
    steps:
    - template: StageTemplates/sonar.yml

- stage: build_test_and_package
  displayName: 'Build, Test, and Package'
  - ${{ if eq(parameters.doNugetPush, true) }}:
    dependsOn: 
      - SonarBuild
  jobs:
  - job: build_and_test_job
    displayName: 'Build, Test, and Package Job'
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      fetchTags: true
      displayName: 'git checkout'
      enabled: true
      retryCountOnTaskFailure: 2

    - template: Common/InstallEnvironment.yaml

    - template: Common/build.yaml

    - template: Common/test.yaml

    - task: DotNetCoreCLI@2
      displayName: 'NuGet Pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(mainProject)'
        versioningScheme: 'off'

    # Conditional NuGet Push
    - ${{ if eq(parameters.doNugetPush, true) }}:
      - task: NuGetCommand@2
        displayName: 'NuGet Push'
        condition: ${{ eq(parameters.doNugetPush, true) }}
        inputs:
          command: 'pack'
          packagesToPack: '$(mainProject)'
          versioningScheme: 'off'
          # command: 'push'
          # packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          # nuGetFeedType: 'external'
          # publishFeedCredentials: 'Nuget BigExcel'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        publishLocation: 'pipeline'
     
- ${{ if eq(parameters.doDocFxPublish, true) }}:  
  - stage: publish_docfx
    displayName: 'Publish DocFX Documentation'
    condition: ${{ eq(parameters.doDocFxPublish, true) }}
    dependsOn:
      - SonarBuild
      - ${{ if eq(parameters.doNugetPush, true) }}:
        - build_test_and_package
    jobs:
    - job: publish_docfx_job
      displayName: 'Publish DocFX Documentation Job'
      pool:
        vmImage: ubuntu-latest
      steps:
        - template: StageTemplates/docfx.yml
      