name: 'BigExcelCreator-sonar'

trigger:
  branches:
    exclude:
      - 'azure-pipelines'
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  mainProject: 'BigExcelCreator/BigExcelCreator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: SonarBuild
  displayName: 'Build and analize with SonarCloud'
  jobs:
  - job: SonarBuildJob
    displayName: 'Prepare, Build, and Analyze'
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      fetchTags: true
      displayName: 'Git Checkout'
      enabled: true
      retryCountOnTaskFailure: 2

    - template: Common/InstallEnvironment.yaml

    - task: SonarCloudPrepare@3
      inputs:
        SonarCloud: 'sonar bigexcel'
        organization: 'fenase-1'
        scannerMode: 'dotnet'
        projectKey: 'fenase_BigExcelCreator'
        projectVersion: '3.0'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.coverage.exclusions=**/Exceptions/**/*.*, Example/**/*.*

    - template: Common/build.yaml

    # Run tests against the downloaded binaries
    - task: VSTest@3
      displayName: 'Run Unit Tests'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\bin\**\*.test.dll
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        diagnosticsEnabled: true

    - task: SonarCloudAnalyze@3
      inputs:
        jdkversion: 'JAVA_HOME_21_X64'

    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        publishLocation: 'pipeline'
