# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  # Step 1: Install DocFX
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'  # Ensure you have .NET SDK installed
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet tool install -g docfx
    displayName: 'Install DocFX'

  # Step 2: Build the Documentation using DocFX
  - script: |
      docfx docfx.json
    displayName: 'Build Documentation'

  # Step 3: Deploy to GitHub Pages
  - task: Bash@3
    displayName: 'Deploy to GitHub Pages'
    inputs:
      targetType: 'inline'
      script: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git clone --branch gh-pages https://$GITHUB_PAT@github.com/$GITHUB_REPO.git out
        rm -rf out/*
        cp -r _site/* out/
        cd out
        git add --all
        git commit -m "Update documentation"
        git push origin gh-pages
    env:
      GITHUB_PAT: $(GITHUB_PAT)  # The GitHub Personal Access Token
      GITHUB_REPO: fenase/BigExcelCreator  # Update with your repo details
