steps:
- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

# Copy build outputs into the artifact staging directory
- task: CopyFiles@2
  displayName: 'Copy Build Outputs to Artifact Staging'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**\bin\$(buildConfiguration)\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
