steps:
- task: DotNetCoreCLI@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    projects: 'BigExcelCreator.sln'


- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration)'

